// <auto-generated />
using System;
using AssetRepository.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AssetRepository.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20201118182444_addednew column")]
    partial class addednewcolumn
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("AssetService.Models.Asset", b =>
                {
                    b.Property<int>("AssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("IsCash")
                        .HasColumnType("bit");

                    b.Property<bool>("IsConvertible")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFuture")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSwap")
                        .HasColumnType("bit");

                    b.Property<bool>("IsfixIncome")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("AssetId");

                    b.ToTable("Assets");

                    b.HasData(
                        new
                        {
                            AssetId = 1,
                            IsCash = true,
                            IsConvertible = false,
                            IsFuture = false,
                            IsSwap = false,
                            IsfixIncome = false,
                            Name = "Asset 1",
                            Timestamp = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            AssetId = 2,
                            IsCash = true,
                            IsConvertible = false,
                            IsFuture = false,
                            IsSwap = false,
                            IsfixIncome = false,
                            Name = "Asset 2",
                            Timestamp = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            AssetId = 3,
                            IsCash = false,
                            IsConvertible = true,
                            IsFuture = false,
                            IsSwap = false,
                            IsfixIncome = false,
                            Name = "Asset 3",
                            Timestamp = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            AssetId = 4,
                            IsCash = false,
                            IsConvertible = false,
                            IsFuture = false,
                            IsSwap = false,
                            IsfixIncome = true,
                            Name = "Asset 4",
                            Timestamp = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            AssetId = 5,
                            IsCash = false,
                            IsConvertible = true,
                            IsFuture = false,
                            IsSwap = false,
                            IsfixIncome = false,
                            Name = "Asset 5",
                            Timestamp = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
